services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dw4imFsyEhSr4
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - kids-stories-network

  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"
    networks:
      - kids-stories-network

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    env_file: backend/.env
    volumes:
      - backend_assets:/app/assets
      - backend_migrations:/app/migrations
    depends_on:
      - db
      - memcached
    networks:
      - kids-stories-network

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    env_file: frontend/.env.production
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    networks:
      - kids-stories-network

volumes:
  db_data:
  backend_assets:
  backend_migrations:

networks:
  kids-stories-network:
    driver: bridge
