services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cN7MILc245qttuNb
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  kids-stories-backend:
    build: backend/
    ports:
      - "5000:5000"
    env_file: backend/.env
    volumes:
      - backend_assets:/app/assets
      - backend_migrations:/app/migrations
    depends_on:
      - db

  kids-stories-frontend:
    build: frontend/
    ports:
      - "80:3000"
    env_file: frontend/.env
    depends_on:
      - kids-stories-backend

volumes:
  db_data:
  backend_assets:
  backend_migrations: